# Generated by Django 6.0.1 on 2026-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricevarieties',
            name='id',
        ),
        migrations.RemoveField(
            model_name='saleproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='ricevarieties',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
