# Generated by Django 6.0.1 on 2026-02-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0002_remove_ricevarieties_id_remove_saleproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='riceprice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
