# Generated by Django 6.0.1 on 2026-02-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0003_alter_learning_id_alter_riceprice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ricevarieties',
            old_name='product_price',
            new_name='product_qty',
        ),
        migrations.AddField(
            model_name='ricevarieties',
            name='phone',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
