# Generated by Django 6.0.1 on 2026-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0004_rename_product_price_ricevarieties_product_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riceprice',
            name='phon',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
