# Generated by Django 6.0.1 on 2026-02-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0005_riceprice_phon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riceprice',
            old_name='phon',
            new_name='phone',
        ),
    ]
